### ISSUE TITLE
Y'a trop d'architectures

### ISSUE THREAD

**Issue by LothaireCliquennois** [Dok-T/android_kernel_alcatel_PIXI5-6_4G#1]
Pas une grande contribution, mais go delete toutes les architectures inutiles...
Au vu du SoC qui est un MediaTek MT67xx(X) c'est dans tout les cas du ARM, donc go enlever tout ce qui sert à rien, genre osef du x86 et tout

**Comment by Dok-T** [comment]
C'est normal. Quand tu compile tu défini ta variable ARCH=arm et ton make va se démerder a compiler pour du ARM. 
Apres une recherche dans le build.prop d'un 9008A c'est plutôt un MTK6737M avec un chip WLAMN MT6735
Donc non tout est normal.

`ro.build.flavor=9008J-user
ro.product.model=9008A
ro.product.brand=TCL
ro.product.name=9008A
ro.product.device=PIXI5-6_4G
ro.product.board=mt6737m
# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,
# use ro.product.cpu.abilist instead.
ro.product.cpu.abi=armeabi-v7a
ro.product.cpu.abi2=armeabi
ro.product.cpu.abilist=armeabi-v7a,armeabi
ro.product.cpu.abilist32=armeabi-v7a,armeabi
ro.product.cpu.abilist64=
ro.product.manufacturer=TCL
ro.wifi.channels=
ro.board.platform=mt6737m


#
# ADDITIONAL_BUILD_PROPERTIES
#
ro.carrier=unknown
dalvik.vm.heapgrowthlimit=128m
dalvik.vm.heapsize=256m
ro.mediatek.chip_ver=S01
ro.mediatek.platform=MT6737M
ro.telephony.sim.count=2
persist.radio.default.sim=0
ril.specific.sm_cause=0
`
